"""Build VoxFusion GUI/CLI binaries with PyInstaller and ZIP packaging.

This script is designed for native builds:
- run on Windows to build Windows binaries
- run on Linux to build Linux binaries
- run on macOS to build macOS binaries
"""

from __future__ import annotations

import argparse
import os
import platform
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
BUILD_DIR = PROJECT_ROOT / "build"
DIST_DIR = PROJECT_ROOT / "dist" / "binaries"
ASSETS_DIR = PROJECT_ROOT / "assets"
VERSION_FILE_PATH = BUILD_DIR / "pyinstaller-version.txt"
VERSION_MODULE_PATH = PROJECT_ROOT / "src" / "voxfusion" / "version.py"

# Per-platform icon file names (generated by scripts/make_icon.py)
_ICON_FILES: dict[str, str] = {
    "windows": "voxfusion.ico",
    "darwin": "voxfusion.icns",
    "linux": "voxfusion.png",
}


@dataclass(frozen=True)
class BinaryTarget:
    """PyInstaller build target."""

    name: str
    entry_module: str
    entry_callable: str
    windowed: bool


TARGETS: dict[str, BinaryTarget] = {
    "gui": BinaryTarget(
        name="voxfusion-gui",
        entry_module="voxfusion.gui.main",
        entry_callable="main",
        windowed=True,
    ),
    "cli": BinaryTarget(
        name="voxfusion-cli",
        entry_module="voxfusion.cli.main",
        entry_callable="main",
        windowed=False,
    ),
}


def _write_launcher(target: BinaryTarget) -> Path:
    """Generate a minimal launcher script in the build directory."""
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    launcher_path = BUILD_DIR / f"{target.name}_launcher.py"
    launcher_path.write_text(
        f"from {target.entry_module} import {target.entry_callable}\n"
        f"if __name__ == '__main__':\n"
        f"    raise SystemExit({target.entry_callable}())\n",
        encoding="utf-8",
    )
    return launcher_path


def parse_args() -> argparse.Namespace:
    """Parse CLI args."""
    parser = argparse.ArgumentParser(description="Build VoxFusion binaries.")
    parser.add_argument(
        "--target",
        choices=["all", "gui", "cli"],
        default="all",
        help="Build target selector.",
    )
    parser.add_argument(
        "--company-name",
        default="VoxFusion Contributors",
        help="Company metadata for Windows version resource.",
    )
    parser.add_argument(
        "--product-name",
        default="VoxFusion",
        help="Product metadata for Windows version resource.",
    )
    parser.add_argument(
        "--no-zip",
        action="store_true",
        help="Skip ZIP archive generation.",
    )
    parser.add_argument(
        "--skip-install",
        action="store_true",
        help="Skip dependency installation step (use current environment as-is).",
    )
    return parser.parse_args()


def load_version() -> tuple[str, tuple[int, int, int, int]]:
    """Load package version from source file."""
    raw_text = VERSION_MODULE_PATH.read_text(encoding="utf-8")
    match = re.search(r'__version__\s*=\s*"([0-9]+\.[0-9]+\.[0-9]+)"', raw_text)
    if not match:
        raise RuntimeError("Unable to parse version from src/voxfusion/version.py")
    version = match.group(1)
    major, minor, patch = (int(part) for part in version.split("."))
    return version, (major, minor, patch, 0)


def write_version_file(
    *,
    company_name: str,
    product_name: str,
    version_str: str,
    version_tuple: tuple[int, int, int, int],
) -> Path:
    """Create a Windows-compatible PyInstaller version file."""
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    version_text = f"""# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', '{company_name}'),
          StringStruct('FileDescription', '{product_name} executable'),
          StringStruct('FileVersion', '{version_str}'),
          StringStruct('InternalName', '{product_name}'),
          StringStruct('LegalCopyright', 'Copyright (C) VoxFusion Contributors'),
          StringStruct('OriginalFilename', '{product_name}.exe'),
          StringStruct('ProductName', '{product_name}'),
          StringStruct('ProductVersion', '{version_str}')
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    VERSION_FILE_PATH.write_text(version_text, encoding="utf-8")
    return VERSION_FILE_PATH


def _is_installed(package: str) -> bool:
    """Return True if *package* is importable in the current environment."""
    import importlib.util
    return importlib.util.find_spec(package.replace("-", "_")) is not None


def _collect_all_packages() -> list[str]:
    """Return the list of packages that need --collect-all.

    Only packages that are actually installed are included so that
    PyInstaller does not fail on missing optional dependencies.
    """
    # Always needed: pyaudiowpatch ships native DLLs that must be collected.
    candidates = ["pyaudiowpatch"]

    # GigaAM backend: bundle tokenizer config JSONs, vocab files, etc.
    # Only included when the user has installed the `gigaam` extra (transformers + torch).
    if _is_installed("transformers"):
        candidates.append("transformers")
        print("[deps] --collect-all transformers  (installed — GigaAM backend active)")
    else:
        print("[deps] skipping --collect-all transformers  (not installed — Whisper-only build)")

    return candidates


def _hidden_imports() -> list[str]:
    """Return hidden imports, adding optional ones only when installed."""
    base: list[str] = [
        # Core inference
        "faster_whisper",
        "ctranslate2",
        # Audio I/O
        "sounddevice",
        "soundfile",
        # VoxFusion internals that PyInstaller may miss due to dynamic imports
        "voxfusion.asr.factory",
        "voxfusion.asr.gigaam_engine",
        "voxfusion.asr.breeze_engine",
        "voxfusion.asr.parakeet_engine",
        "voxfusion.asr.faster_whisper",
        "voxfusion.capture.wasapi",
        "pyaudiowpatch",
        "voxfusion.capture.vad_chunker",
        "voxfusion.capture.mixer",
        "voxfusion.media.extractor",
        "voxfusion.pipeline.orchestrator",
        "voxfusion.pipeline.batch",
        "voxfusion.pipeline.streaming",
        "voxfusion.translation.registry",
        "voxfusion.translation.argos_engine",
        # Logging
        "structlog",
        # GUI
        "tkinter",
        "tkinter.ttk",
        "tkinter.scrolledtext",
        "tkinter.filedialog",
    ]

    # Optional: engine-specific imports — only bundled when actually installed.
    optional: dict[str, list[str]] = {
        "transformers": ["transformers"],   # GigaAM backend
        "scipy": ["scipy", "scipy.signal"],
        "nemo": ["nemo.collections.asr"],   # Parakeet backend
    }
    for check_pkg, imports in optional.items():
        if _is_installed(check_pkg):
            base.extend(imports)

    return base


def _install_dependencies() -> None:
    """Install all project dependencies into the current Python environment.

    Uses ``pip install`` with the project's ``pyproject.toml``-declared
    requirements so the PyInstaller bundle contains every needed package.
    Prefer poetry if available; fall back to plain pip.
    """
    print("\n[deps] Installing / verifying project dependencies...")

    # Determine platform-specific extras
    extras = []
    if platform.system().lower() == "windows":
        extras.append("windows")

    # Try poetry first (handles version constraints best)
    if shutil.which("poetry"):
        cmd = ["poetry", "install", "--no-interaction"]
        print(f"[deps] {' '.join(cmd)}")
        result = subprocess.run(cmd, cwd=PROJECT_ROOT)
        if result.returncode == 0:
            print("[deps] poetry install succeeded.")
            return
        print("[deps] poetry install failed — falling back to pip.")

    # Fall back to pip install -e .
    extra_str = f"[{','.join(extras)}]" if extras else ""
    pip_cmd = [
        sys.executable, "-m", "pip", "install", "--upgrade",
        f".{extra_str}",
    ]
    print(f"[deps] {' '.join(pip_cmd)}")
    result = subprocess.run(pip_cmd, cwd=PROJECT_ROOT)
    if result.returncode != 0:
        print("[deps] WARNING: pip install returned non-zero. Continuing anyway.")

    print("[deps] Dependency installation complete.\n")


def _generate_icons() -> None:
    """Generate application icons via scripts/make_icon.py (requires Pillow)."""
    try:
        from PIL import Image, ImageDraw  # noqa: F401
    except ImportError:
        print("[icon] Pillow not installed — skipping icon generation (pip install Pillow)")
        return

    make_icon = Path(__file__).resolve().parent / "make_icon.py"
    if not make_icon.exists():
        print(f"[icon] {make_icon} not found — skipping")
        return

    import importlib.util
    spec = importlib.util.spec_from_file_location("make_icon", make_icon)
    mod = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    mod.main()


def _get_icon_path() -> Path | None:
    """Return the platform-specific icon path, generating icons first if needed."""
    system = platform.system().lower()
    name = _ICON_FILES.get(system)
    preferred = ASSETS_DIR / name if name else None

    if preferred and preferred.exists():
        return preferred

    # Icons missing — generate them on the fly
    _generate_icons()

    if preferred and preferred.exists():
        return preferred
    ico = ASSETS_DIR / "voxfusion.ico"
    if ico.exists():
        return ico

    print("[icon] WARNING: icon generation failed — building without icon")
    return None


def _find_ffmpeg_binary() -> Path | None:
    """Locate the ffmpeg binary in PATH for optional bundling."""
    import shutil
    binary_name = "ffmpeg.exe" if platform.system().lower() == "windows" else "ffmpeg"
    found = shutil.which(binary_name) or shutil.which("ffmpeg")
    return Path(found) if found else None


def _customtkinter_data_entries() -> list[str]:
    """Collect customtkinter theme paths when package is installed."""
    try:
        import customtkinter  # type: ignore[import-not-found]
    except ImportError:
        return []

    package_root = Path(customtkinter.__file__).resolve().parent
    themes_dir = package_root / "assets" / "themes"
    if not themes_dir.exists():
        return []

    return [f"{themes_dir}{os.pathsep}customtkinter/assets/themes"]


def _default_data_entries() -> list[str]:
    defaults_yaml = PROJECT_ROOT / "src" / "voxfusion" / "config" / "defaults.yaml"
    entries = [f"{defaults_yaml}{os.pathsep}voxfusion/config"]
    entries.extend(_customtkinter_data_entries())

    # Bundle ffmpeg binary if found in PATH so the distributable works without
    # a system ffmpeg install.  The binary lands next to the executable.
    ffmpeg = _find_ffmpeg_binary()
    if ffmpeg and ffmpeg.exists():
        entries.append(f"{ffmpeg}{os.pathsep}.")
        print(f"[ffmpeg] bundling {ffmpeg}")
    else:
        print(
            "[ffmpeg] WARNING: ffmpeg not found in PATH — video file support will "
            "require users to install FFmpeg separately.\n"
            "  Windows: https://www.gyan.dev/ffmpeg/builds/\n"
            "  Linux:   sudo apt install ffmpeg"
        )

    return entries


def _platform_tag() -> str:
    machine = platform.machine().lower() or "unknown"
    system_name = platform.system().lower() or "unknown"
    return f"{system_name}-{machine}"


def _copy_python_dll(bundle_dir: Path) -> None:
    """Copy python3XX.dll next to the EXE for reliable loading on Windows.

    PyInstaller places the DLL in _internal/ and uses SetDllDirectory to
    expose it, but some Windows 11 security configurations prevent this.
    Having the DLL in the same directory as the EXE is always found first
    by the Windows DLL loader without any extra API calls.
    """
    if platform.system().lower() != "windows":
        return
    dll_name = f"python{sys.version_info.major}{sys.version_info.minor}.dll"
    src = Path(sys.executable).parent / dll_name
    if not src.exists():
        print(f"[dll] WARNING: {dll_name} not found at {src}, skipping copy")
        return
    dst = bundle_dir / dll_name
    if not dst.exists():
        shutil.copy2(src, dst)
        print(f"[dll] copied {dll_name} to bundle root for reliable loading")


def build_target(
    target: BinaryTarget,
    *,
    version_file: Path,
    include_zip: bool,
) -> Path:
    """Build one binary target and optionally package to ZIP."""
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    pyinstaller_work = BUILD_DIR / "pyinstaller-work" / target.name
    pyinstaller_spec = BUILD_DIR / "pyinstaller-spec"
    pyinstaller_work.mkdir(parents=True, exist_ok=True)
    pyinstaller_spec.mkdir(parents=True, exist_ok=True)

    command = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        "--onedir",
        "--name",
        target.name,
        "--distpath",
        str(DIST_DIR),
        "--workpath",
        str(pyinstaller_work),
        "--specpath",
        str(pyinstaller_spec),
    ]

    if platform.system().lower() == "windows" and version_file.exists():
        command.extend(["--version-file", str(version_file)])

    icon = _get_icon_path()
    if icon:
        command.extend(["--icon", str(icon)])
        print(f"[icon] {icon}")
    else:
        print(
            "[icon] WARNING: no icon found in assets/.\n"
            "  Run: python scripts/make_icon.py   (requires: pip install Pillow)"
        )

    command.append("--windowed" if target.windowed else "--console")

    for imp in _hidden_imports():
        command.extend(["--hidden-import", imp])

    # Collect all files (including native DLLs) from packages that need it.
    # Only packages that are actually installed are included.
    for pkg in _collect_all_packages():
        command.extend(["--collect-all", pkg])

    for entry in _default_data_entries():
        command.extend(["--add-data", entry])

    launcher = _write_launcher(target)
    command.append(str(launcher))

    print(f"\n[build] {target.name}")
    print(" ".join(command))
    subprocess.run(command, cwd=PROJECT_ROOT, check=True)

    bundle_dir = DIST_DIR / target.name
    _copy_python_dll(bundle_dir)
    if not include_zip:
        return bundle_dir

    archive_basename = DIST_DIR / f"{target.name}-{_platform_tag()}"
    zip_path = archive_basename.with_suffix(".zip")
    if zip_path.exists():
        zip_path.unlink()

    shutil.make_archive(
        base_name=str(archive_basename),
        format="zip",
        root_dir=str(DIST_DIR),
        base_dir=target.name,
    )
    print(f"[zip] {zip_path}")
    return zip_path


def main() -> int:
    """Main build flow."""
    args = parse_args()

    if not args.skip_install:
        _install_dependencies()
    else:
        print("[deps] Skipping dependency installation (--skip-install).")

    version, version_tuple = load_version()
    version_file = write_version_file(
        company_name=args.company_name,
        product_name=args.product_name,
        version_str=version,
        version_tuple=version_tuple,
    )

    selected_targets: list[BinaryTarget]
    if args.target == "all":
        selected_targets = [TARGETS["gui"], TARGETS["cli"]]
    else:
        selected_targets = [TARGETS[args.target]]

    for target in selected_targets:
        build_target(
            target,
            version_file=version_file,
            include_zip=not args.no_zip,
        )

    print("\nBuild completed.")
    if platform.system().lower() == "windows":
        print(
            "Windows note: ask users to open ZIP file properties and click "
            "'Unblock' before extraction."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
