"""Build VoxFusion GUI/CLI binaries with PyInstaller and ZIP packaging.

This script is designed for native builds:
- run on Windows to build Windows binaries
- run on Linux to build Linux binaries
- run on macOS to build macOS binaries
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import platform
import re
import shutil
import subprocess
import sys
import urllib.request
import zipfile
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
BUILD_DIR = PROJECT_ROOT / "build"
DIST_DIR = PROJECT_ROOT / "dist" / "binaries"
ASSETS_DIR = PROJECT_ROOT / "assets"
VERSION_FILE_PATH = BUILD_DIR / "pyinstaller-version.txt"
VERSION_MODULE_PATH = PROJECT_ROOT / "src" / "voxfusion" / "version.py"
FFMPEG_VENDOR_DIR = BUILD_DIR / "vendor" / "ffmpeg"
WINDOWS_FFMPEG_SHARED_URL = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z"
WINDOWS_FFMPEG_ESSENTIALS_URL = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"
LINUX_FFMPEG_STATIC_URL = "https://johnvansickle.com/ffmpeg/releases/release-{arch}-static.tar.xz"
MACOS_FFMPEG_URL = "https://evermeet.cx/ffmpeg/getrelease/{binary}/zip"

# Per-platform icon file names (generated by scripts/make_icon.py)
_ICON_FILES: dict[str, str] = {
    "windows": "voxfusion.ico",
    "darwin": "voxfusion.icns",
    "linux": "voxfusion.png",
}


@dataclass(frozen=True)
class BinaryTarget:
    """PyInstaller build target."""

    name: str
    entry_module: str
    entry_callable: str
    windowed: bool


TARGETS: dict[str, BinaryTarget] = {
    "gui": BinaryTarget(
        name="voxfusion-gui",
        entry_module="voxfusion.gui.main",
        entry_callable="main",
        windowed=True,
    ),
    "cli": BinaryTarget(
        name="voxfusion-cli",
        entry_module="voxfusion.cli.main",
        entry_callable="main",
        windowed=False,
    ),
}


def _write_launcher(target: BinaryTarget) -> Path:
    """Generate a minimal launcher script in the build directory."""
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    launcher_path = BUILD_DIR / f"{target.name}_launcher.py"
    launcher_path.write_text(
        f"from {target.entry_module} import {target.entry_callable}\n"
        f"if __name__ == '__main__':\n"
        f"    raise SystemExit({target.entry_callable}())\n",
        encoding="utf-8",
    )
    return launcher_path


def parse_args() -> argparse.Namespace:
    """Parse CLI args."""
    parser = argparse.ArgumentParser(description="Build VoxFusion binaries.")
    parser.add_argument(
        "--target",
        choices=["all", "gui", "cli"],
        default="all",
        help="Build target selector.",
    )
    parser.add_argument(
        "--company-name",
        default="VoxFusion Contributors",
        help="Company metadata for Windows version resource.",
    )
    parser.add_argument(
        "--product-name",
        default="VoxFusion",
        help="Product metadata for Windows version resource.",
    )
    parser.add_argument(
        "--no-zip",
        action="store_true",
        help="Skip ZIP archive generation.",
    )
    parser.add_argument(
        "--skip-install",
        action="store_true",
        help="Skip dependency installation step (use current environment as-is).",
    )
    parser.add_argument(
        "--backends",
        default="whisper",
        metavar="LIST",
        help=(
            "Comma-separated list of ASR backends to bundle. "
            "Default: 'whisper' (~140 MB, fast build). "
            "Options: whisper, gigaam, breeze, parakeet, all. "
            "Example: --backends gigaam  or  --backends gigaam,breeze"
        ),
    )
    return parser.parse_args()


def load_version() -> tuple[str, tuple[int, int, int, int]]:
    """Load package version from source file."""
    raw_text = VERSION_MODULE_PATH.read_text(encoding="utf-8")
    match = re.search(r'__version__\s*=\s*"([0-9]+\.[0-9]+\.[0-9]+)"', raw_text)
    if not match:
        raise RuntimeError("Unable to parse version from src/voxfusion/version.py")
    version = match.group(1)
    major, minor, patch = (int(part) for part in version.split("."))
    return version, (major, minor, patch, 0)


def write_version_file(
    *,
    company_name: str,
    product_name: str,
    version_str: str,
    version_tuple: tuple[int, int, int, int],
) -> Path:
    """Create a Windows-compatible PyInstaller version file."""
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    version_text = f"""# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', '{company_name}'),
          StringStruct('FileDescription', '{product_name} executable'),
          StringStruct('FileVersion', '{version_str}'),
          StringStruct('InternalName', '{product_name}'),
          StringStruct('LegalCopyright', 'Copyright (C) VoxFusion Contributors'),
          StringStruct('OriginalFilename', '{product_name}.exe'),
          StringStruct('ProductName', '{product_name}'),
          StringStruct('ProductVersion', '{version_str}')
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    VERSION_FILE_PATH.write_text(version_text, encoding="utf-8")
    return VERSION_FILE_PATH


def _is_installed(package: str) -> bool:
    """Return True if *package* is importable in the current environment."""
    try:
        return importlib.util.find_spec(package.replace("-", "_")) is not None
    except (ImportError, ModuleNotFoundError, ValueError):
        return False


def _safe_find_spec(module_name: str):
    """Return `find_spec(module_name)` or `None` when parent modules are absent."""
    try:
        return importlib.util.find_spec(module_name)
    except (ImportError, ModuleNotFoundError, ValueError):
        return None


def _parse_backends(backends_arg: str) -> set[str]:
    """Return the normalised set of requested backend names.

    Accepts a comma-separated string such as ``"gigaam,breeze"`` or ``"all"``.
    ``"all"`` expands to every known backend.
    """
    known = {"whisper", "gigaam", "breeze", "parakeet"}
    raw = {b.strip().lower() for b in backends_arg.split(",") if b.strip()}
    if "all" in raw:
        return known
    unknown = raw - known
    if unknown:
        print(
            f"[backends] WARNING: unknown backend(s): {', '.join(sorted(unknown))}. "
            f"Known: {', '.join(sorted(known))}"
        )
    return raw


def _collect_all_packages(*, backends: set[str]) -> list[str]:
    """Return the list of packages that need --collect-all.

    Only packages that are actually installed are included so that
    PyInstaller does not fail on missing optional dependencies.
    """
    # Always needed: pyaudiowpatch ships native DLLs that must be collected.
    candidates = ["pyaudiowpatch"]

    needs_torch = backends & {"gigaam", "breeze", "parakeet"}

    # pyannote.audio pulls torch transitively; --collect-all triggers
    # PyInstaller's _collect_submodules('torch.distributed.optim') which
    # segfaults on Linux.  Only include pyannote when torch backends are
    # explicitly requested (they already collect-all torch anyway).
    if needs_torch and _is_installed("pyannote.audio"):
        candidates.append("pyannote.audio")
        print("[deps] --collect-all pyannote.audio  (ML diarization / speaker detect)")
    elif _is_installed("pyannote.audio"):
        print(
            "[deps] skipping --collect-all pyannote.audio (torch not in backends, avoids segfault)"
        )
    else:
        print(
            "[deps] WARNING: pyannote.audio not installed — ML diarization and speaker detect won't work"
        )

    needs_torch = backends & {"gigaam", "breeze", "parakeet"}
    needs_transformers = backends & {"gigaam", "breeze"}

    if needs_torch:
        if _is_installed("torch"):
            candidates.append("torch")
            print(f"[deps] --collect-all torch  (backends: {', '.join(sorted(needs_torch))})")
        else:
            print(
                f"[deps] WARNING: torch not installed — backends {', '.join(sorted(needs_torch))} won't work"
            )

    if needs_transformers:
        if _is_installed("transformers"):
            candidates.append("transformers")
            print(
                f"[deps] --collect-all transformers  (backends: {', '.join(sorted(needs_transformers))})"
            )
        else:
            print(
                f"[deps] WARNING: transformers not installed — backends {', '.join(sorted(needs_transformers))} won't work"
            )

    if not needs_torch:
        print(
            f"[deps] skipping --collect-all torch/transformers  (backends: {', '.join(sorted(backends))})"
        )

    return candidates


def _hidden_imports(*, backends: set[str]) -> list[str]:
    """Return hidden imports, adding optional ones only when installed."""
    base: list[str] = [
        # Core inference
        "faster_whisper",
        "ctranslate2",
        # Audio I/O
        "sounddevice",
        "soundfile",
        # VoxFusion internals that PyInstaller may miss due to dynamic imports
        "voxfusion.asr.factory",
        "voxfusion.asr.gigaam_engine",
        "voxfusion.asr.breeze_engine",
        "voxfusion.asr.parakeet_engine",
        "voxfusion.asr.faster_whisper",
        "voxfusion.capture.wasapi",
        "pyaudiowpatch",
        "voxfusion.capture.vad_chunker",
        "voxfusion.capture.mixer",
        "voxfusion.media.extractor",
        "voxfusion.pipeline.orchestrator",
        "voxfusion.pipeline.batch",
        "voxfusion.pipeline.streaming",
        "voxfusion.diarization.factory",
        "voxfusion.diarization.chunked",
        "voxfusion.diarization.pyannote_engine",
        "voxfusion.diarization.speaker_counter",
        "voxfusion.translation.registry",
        "voxfusion.translation.argos_engine",
        # Logging
        "structlog",
        # GUI
        "tkinter",
        "tkinter.ttk",
        "tkinter.scrolledtext",
        "tkinter.filedialog",
    ]

    # Optional: engine-specific imports — only bundled for selected backends.
    optional: dict[str, list[str]] = {}

    if backends & {"gigaam", "breeze", "parakeet"}:
        optional["torch"] = ["torch", "torch.nn", "torch.nn.functional"]

    if backends & {"gigaam", "breeze"}:
        optional["transformers"] = [
            "transformers",
            # Breeze uses WhisperProcessor directly — explicit import avoids
            # AutoProcessor auto-class resolution which fails in frozen binaries.
            "transformers.models.whisper.processing_whisper",
            "transformers.models.whisper.modeling_whisper",
            "transformers.pipelines.automatic_speech_recognition",
        ]
        optional["huggingface_hub"] = ["huggingface_hub"]  # snapshot_download for model downloads

    if "parakeet" in backends:
        optional["nemo"] = ["nemo.collections.asr"]

    optional["scipy"] = ["scipy", "scipy.signal"]

    for check_pkg, imports in optional.items():
        if _is_installed(check_pkg):
            base.extend(imports)

    return base


def _install_dependencies() -> None:
    """Install all project dependencies into the current Python environment.

    Uses ``pip install`` with the project's ``pyproject.toml``-declared
    requirements so the PyInstaller bundle contains every needed package.
    Prefer poetry if available; fall back to plain pip.
    """
    print("\n[deps] Installing / verifying project dependencies...")

    # Determine platform-specific extras
    extras = []
    if platform.system().lower() == "windows":
        extras.append("windows")

    # Only use poetry when the script itself is already running inside the
    # poetry-managed environment. Otherwise `poetry install` may populate a
    # different interpreter than the one that later runs PyInstaller.
    if shutil.which("poetry") and os.environ.get("POETRY_ACTIVE") == "1":
        cmd = ["poetry", "install", "--no-interaction"]
        print(f"[deps] {' '.join(cmd)}")
        result = subprocess.run(cmd, cwd=PROJECT_ROOT, check=False)
        if result.returncode == 0:
            print("[deps] poetry install succeeded.")
            return
        print("[deps] poetry install failed — falling back to pip.")
    elif shutil.which("poetry"):
        print(
            "[deps] poetry detected but this script is not running inside `poetry run`.\n"
            "[deps] Installing into the current interpreter via pip to keep build/install environments aligned."
        )

    # Fall back to pip install -e .
    extra_str = f"[{','.join(extras)}]" if extras else ""
    pip_cmd = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--upgrade",
        f".{extra_str}",
    ]
    print(f"[deps] {' '.join(pip_cmd)}")
    result = subprocess.run(pip_cmd, cwd=PROJECT_ROOT, check=False)
    if result.returncode != 0:
        print("[deps] WARNING: pip install returned non-zero. Continuing anyway.")

    print("[deps] Dependency installation complete.\n")


def _generate_icons() -> None:
    """Generate application icons via scripts/make_icon.py (requires Pillow)."""
    try:
        from PIL import Image, ImageDraw  # noqa: F401
    except ImportError:
        print("[icon] Pillow not installed — skipping icon generation (pip install Pillow)")
        return

    make_icon = Path(__file__).resolve().parent / "make_icon.py"
    if not make_icon.exists():
        print(f"[icon] {make_icon} not found — skipping")
        return

    import importlib.util

    spec = importlib.util.spec_from_file_location("make_icon", make_icon)
    mod = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    mod.main()


def _get_icon_path() -> Path | None:
    """Return the platform-specific icon path, generating icons first if needed."""
    system = platform.system().lower()
    name = _ICON_FILES.get(system)
    preferred = ASSETS_DIR / name if name else None

    if preferred and preferred.exists():
        return preferred

    # Icons missing — generate them on the fly
    _generate_icons()

    if preferred and preferred.exists():
        return preferred
    ico = ASSETS_DIR / "voxfusion.ico"
    if ico.exists():
        return ico

    print("[icon] WARNING: icon generation failed — building without icon")
    return None


def _find_ffmpeg_binary() -> Path | None:
    """Locate the ffmpeg binary in PATH for optional bundling."""
    import shutil

    binary_name = "ffmpeg.exe" if platform.system().lower() == "windows" else "ffmpeg"
    found = shutil.which(binary_name) or shutil.which("ffmpeg")
    return Path(found).resolve() if found else None


def _find_7z_executable() -> str | None:
    for candidate in ("7z", "7za"):
        found = shutil.which(candidate)
        if found:
            return found
    return None


def _extract_ffmpeg_binaries_from_zip(zip_path: Path, target_dir: Path) -> Path:
    """Extract `ffmpeg(.exe)`, `ffprobe(.exe)`, and shared DLLs from a ZIP."""
    target_dir.mkdir(parents=True, exist_ok=True)
    ffmpeg_path: Path | None = None
    with zipfile.ZipFile(zip_path) as archive:
        members = {name.lower(): name for name in archive.namelist()}
        for lowered, member in members.items():
            if (
                not lowered.endswith(".dll")
                and not lowered.endswith("/bin/ffmpeg.exe")
                and not lowered.endswith("/bin/ffprobe.exe")
            ):
                continue
            output_path = target_dir / Path(member).name
            with archive.open(member) as src, output_path.open("wb") as dst:
                shutil.copyfileobj(src, dst)
            if output_path.name.lower() == "ffmpeg.exe":
                ffmpeg_path = output_path
    if ffmpeg_path is None or not ffmpeg_path.exists():
        raise RuntimeError("Downloaded FFmpeg archive did not contain bin/ffmpeg.exe")
    return ffmpeg_path


def _extract_ffmpeg_binaries_from_7z(archive_path: Path, target_dir: Path) -> Path:
    """Extract FFmpeg binaries and shared DLLs from a 7z archive."""
    target_dir.mkdir(parents=True, exist_ok=True)
    extractor = _find_7z_executable()
    if extractor is None:
        raise RuntimeError("7z/7za is required to unpack the shared FFmpeg archive")

    command = [
        extractor,
        "e",
        "-y",
        f"-o{target_dir}",
        str(archive_path),
        "*/bin/ffmpeg.exe",
        "*/bin/ffprobe.exe",
        "*/bin/*.dll",
    ]
    result = subprocess.run(command, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "7z extraction failed")

    ffmpeg_path = target_dir / "ffmpeg.exe"
    if not ffmpeg_path.exists():
        raise RuntimeError("Downloaded FFmpeg archive did not contain bin/ffmpeg.exe")
    return ffmpeg_path


def _extract_ffmpeg_binaries(archive_path: Path, target_dir: Path) -> Path:
    if archive_path.suffix.lower() == ".zip":
        return _extract_ffmpeg_binaries_from_zip(archive_path, target_dir)
    if archive_path.suffix.lower() == ".7z":
        return _extract_ffmpeg_binaries_from_7z(archive_path, target_dir)
    raise RuntimeError(f"Unsupported FFmpeg archive format: {archive_path.suffix}")


def _ensure_windows_ffmpeg_binary() -> Path | None:
    """Download/extract a portable Windows FFmpeg if PATH does not provide one."""
    if platform.system().lower() != "windows":
        return None

    vendor_ffmpeg = FFMPEG_VENDOR_DIR / "ffmpeg.exe"
    if vendor_ffmpeg.exists():
        return vendor_ffmpeg

    FFMPEG_VENDOR_DIR.mkdir(parents=True, exist_ok=True)
    archives = [
        (
            FFMPEG_VENDOR_DIR / "ffmpeg-release-full-shared.7z",
            WINDOWS_FFMPEG_SHARED_URL,
            "[ffmpeg] PATH is missing FFmpeg — downloading shared portable build for bundling...",
        ),
        (
            FFMPEG_VENDOR_DIR / "ffmpeg-release-essentials.zip",
            WINDOWS_FFMPEG_ESSENTIALS_URL,
            "[ffmpeg] PATH is missing FFmpeg — downloading portable build for bundling...",
        ),
    ]

    last_error: Exception | None = None
    for archive_path, url, message in archives:
        try:
            if not archive_path.exists():
                print(message)
                with urllib.request.urlopen(url, timeout=120) as response:
                    archive_path.write_bytes(response.read())
            ffmpeg = _extract_ffmpeg_binaries(archive_path, FFMPEG_VENDOR_DIR)
            print(f"[ffmpeg] prepared portable FFmpeg at {ffmpeg}")
            return ffmpeg
        except Exception as exc:
            last_error = exc
            print(f"[ffmpeg] WARNING: failed to prepare {archive_path.name}: {exc}")
    if last_error is not None:
        raise last_error
    return None


def _detect_linux_distro() -> str:
    """Detect the Linux distribution ID from /etc/os-release."""
    os_release = Path("/etc/os-release")
    if os_release.exists():
        for line in os_release.read_text(encoding="utf-8").splitlines():
            if line.startswith("ID="):
                return line.split("=", 1)[1].strip('"').strip("'").lower()
    return "unknown"


def _show_ffmpeg_install_hint() -> None:
    """Print platform-specific FFmpeg installation instructions."""
    system = platform.system().lower()
    print(
        "[ffmpeg] WARNING: ffmpeg not found and auto-download failed.\n"
        "  Video file support will require users to install FFmpeg separately."
    )
    if system == "linux":
        distro = _detect_linux_distro()
        hints: dict[str, str] = {
            "debian": "sudo apt install ffmpeg",
            "ubuntu": "sudo apt install ffmpeg",
            "linuxmint": "sudo apt install ffmpeg",
            "pop": "sudo apt install ffmpeg",
            "elementary": "sudo apt install ffmpeg",
            "fedora": "sudo dnf install ffmpeg  (requires RPM Fusion)",
            "rhel": "sudo dnf install ffmpeg  (requires EPEL + RPM Fusion)",
            "centos": "sudo dnf install ffmpeg  (requires EPEL + RPM Fusion)",
            "rocky": "sudo dnf install ffmpeg  (requires EPEL + RPM Fusion)",
            "almalinux": "sudo dnf install ffmpeg  (requires EPEL + RPM Fusion)",
            "arch": "sudo pacman -S ffmpeg",
            "manjaro": "sudo pacman -S ffmpeg",
            "endeavouros": "sudo pacman -S ffmpeg",
            "garuda": "sudo pacman -S ffmpeg",
            "opensuse-leap": "sudo zypper install ffmpeg  (requires Packman repo)",
            "opensuse-tumbleweed": "sudo zypper install ffmpeg  (requires Packman repo)",
            "sles": "sudo zypper install ffmpeg",
            "alpine": "sudo apk add ffmpeg",
            "gentoo": "sudo emerge media-video/ffmpeg",
            "void": "sudo xbps-install ffmpeg",
            "nixos": "nix-env -iA nixos.ffmpeg",
            "solus": "sudo eopkg install ffmpeg",
        }
        cmd = hints.get(distro)
        if cmd:
            print(f"  Detected distro: {distro}\n  Install with: {cmd}")
        else:
            print(
                f"  Detected distro: {distro}\n"
                "  Common install commands:\n"
                "    Debian/Ubuntu/Mint:  sudo apt install ffmpeg\n"
                "    Fedora/RHEL:        sudo dnf install ffmpeg\n"
                "    Arch/Manjaro:       sudo pacman -S ffmpeg\n"
                "    openSUSE:           sudo zypper install ffmpeg\n"
                "    Alpine:             sudo apk add ffmpeg\n"
                "    Void:               sudo xbps-install ffmpeg\n"
                "    NixOS:              nix-env -iA nixos.ffmpeg"
            )
    elif system == "darwin":
        print(
            "  Install with one of:\n"
            "    Homebrew:  brew install ffmpeg\n"
            "    MacPorts:  port install ffmpeg\n"
            "    Download:  https://ffmpeg.org/download.html"
        )
    elif system == "windows":
        print(
            "  Download from: https://www.gyan.dev/ffmpeg/builds/\n"
            "  Or install via: winget install ffmpeg\n"
            "  Or: choco install ffmpeg"
        )


def _ensure_linux_ffmpeg_binary() -> Path | None:
    """Download a static FFmpeg build for Linux if PATH doesn't provide one."""
    machine = platform.machine().lower()
    arch_map: dict[str, str] = {
        "x86_64": "amd64",
        "amd64": "amd64",
        "aarch64": "arm64",
        "arm64": "arm64",
        "armv7l": "armhf",
        "armhf": "armhf",
    }
    arch = arch_map.get(machine)
    if not arch:
        print(f"[ffmpeg] No static build available for architecture: {machine}")
        return None

    FFMPEG_VENDOR_DIR.mkdir(parents=True, exist_ok=True)
    vendor_ffmpeg = FFMPEG_VENDOR_DIR / "ffmpeg"
    if vendor_ffmpeg.exists():
        print(f"[ffmpeg] using cached static build at {vendor_ffmpeg}")
        return vendor_ffmpeg

    url = LINUX_FFMPEG_STATIC_URL.format(arch=arch)
    archive_path = FFMPEG_VENDOR_DIR / f"ffmpeg-{arch}-static.tar.xz"
    print(f"[ffmpeg] Downloading static FFmpeg for Linux {arch}...")
    try:
        with urllib.request.urlopen(url, timeout=180) as response:
            archive_path.write_bytes(response.read())
    except Exception as exc:
        print(f"[ffmpeg] WARNING: failed to download: {exc}")
        return None

    # Extract ffmpeg and ffprobe from the archive.
    import tarfile

    try:
        with tarfile.open(archive_path) as tar:
            for member in tar.getmembers():
                name = Path(member.name).name
                if name in ("ffmpeg", "ffprobe") and not member.isdir():
                    dest = FFMPEG_VENDOR_DIR / name
                    src_file = tar.extractfile(member)
                    if src_file:
                        with src_file, dest.open("wb") as dst:
                            shutil.copyfileobj(src_file, dst)
                        dest.chmod(0o755)
    except Exception as exc:
        print(f"[ffmpeg] WARNING: failed to extract archive: {exc}")
        return None

    if vendor_ffmpeg.exists():
        print(f"[ffmpeg] prepared static FFmpeg at {vendor_ffmpeg}")
        return vendor_ffmpeg

    print("[ffmpeg] WARNING: ffmpeg binary not found in downloaded archive")
    return None


def _ensure_macos_ffmpeg_binary() -> Path | None:
    """Download FFmpeg for macOS if PATH and Homebrew don't provide one."""
    # Check Homebrew first
    brew = shutil.which("brew")
    if brew:
        result = subprocess.run(
            ["brew", "--prefix", "ffmpeg"],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            ffmpeg = Path(result.stdout.strip()) / "bin" / "ffmpeg"
            if ffmpeg.exists():
                print(f"[ffmpeg] found Homebrew FFmpeg at {ffmpeg}")
                return ffmpeg

    FFMPEG_VENDOR_DIR.mkdir(parents=True, exist_ok=True)
    vendor_ffmpeg = FFMPEG_VENDOR_DIR / "ffmpeg"
    if vendor_ffmpeg.exists():
        print(f"[ffmpeg] using cached build at {vendor_ffmpeg}")
        return vendor_ffmpeg

    # Try downloading from evermeet.cx
    import io

    print("[ffmpeg] Downloading FFmpeg for macOS...")
    try:
        url = MACOS_FFMPEG_URL.format(binary="ffmpeg")
        with urllib.request.urlopen(url, timeout=120) as response:
            data = response.read()

        with zipfile.ZipFile(io.BytesIO(data)) as zf:
            for name in zf.namelist():
                if Path(name).name.lower() == "ffmpeg":
                    with zf.open(name) as src, vendor_ffmpeg.open("wb") as dst:
                        shutil.copyfileobj(src, dst)
                    vendor_ffmpeg.chmod(0o755)
                    break

        if not vendor_ffmpeg.exists():
            print("[ffmpeg] WARNING: ffmpeg binary not found in downloaded archive")
            return None

        # Also download ffprobe
        try:
            vendor_ffprobe = FFMPEG_VENDOR_DIR / "ffprobe"
            url_probe = MACOS_FFMPEG_URL.format(binary="ffprobe")
            with urllib.request.urlopen(url_probe, timeout=120) as response:
                data = response.read()
            with zipfile.ZipFile(io.BytesIO(data)) as zf:
                for name in zf.namelist():
                    if Path(name).name.lower() == "ffprobe":
                        with zf.open(name) as src, vendor_ffprobe.open("wb") as dst:
                            shutil.copyfileobj(src, dst)
                        vendor_ffprobe.chmod(0o755)
                        break
        except Exception:
            pass  # ffprobe is optional

        print(f"[ffmpeg] prepared FFmpeg at {vendor_ffmpeg}")
        return vendor_ffmpeg
    except Exception as exc:
        print(f"[ffmpeg] WARNING: failed to download FFmpeg: {exc}")
        return None


def _ffmpeg_data_entries() -> list[str]:
    """Return data entries for bundling FFmpeg/FFprobe into the app root."""
    ffmpeg = _find_ffmpeg_binary()
    if ffmpeg and ffmpeg.exists():
        print(f"[ffmpeg] bundling {ffmpeg}")
    else:
        system = platform.system().lower()
        try:
            if system == "windows":
                ffmpeg = _ensure_windows_ffmpeg_binary()
            elif system == "linux":
                ffmpeg = _ensure_linux_ffmpeg_binary()
            elif system == "darwin":
                ffmpeg = _ensure_macos_ffmpeg_binary()
        except Exception as exc:
            ffmpeg = None
            print(f"[ffmpeg] WARNING: failed to prepare FFmpeg: {exc}")

    if ffmpeg is None or not ffmpeg.exists():
        _show_ffmpeg_install_hint()
        return []

    entries = [f"{ffmpeg}{os.pathsep}."]
    ffprobe = ffmpeg.with_name("ffprobe.exe" if ffmpeg.suffix.lower() == ".exe" else "ffprobe")
    if ffprobe.exists():
        entries.append(f"{ffprobe}{os.pathsep}.")
    for dll in sorted(ffmpeg.parent.glob("*.dll")):
        entries.append(f"{dll}{os.pathsep}.")
    return entries


def _customtkinter_data_entries() -> list[str]:
    """Collect customtkinter theme paths when package is installed."""
    try:
        import customtkinter  # type: ignore[import-not-found]
    except ImportError:
        return []

    package_root = Path(customtkinter.__file__).resolve().parent
    themes_dir = package_root / "assets" / "themes"
    if not themes_dir.exists():
        return []

    return [f"{themes_dir}{os.pathsep}customtkinter/assets/themes"]


def _pyannote_data_entries() -> list[str]:
    """Collect pyannote runtime data files required in frozen bundles."""
    spec = _safe_find_spec("pyannote.audio.telemetry")
    if spec is None or spec.origin is None:
        return []

    telemetry_dir = Path(spec.origin).resolve().parent
    config_path = telemetry_dir / "config.yaml"
    if not config_path.exists():
        print(
            "[deps] WARNING: pyannote telemetry config.yaml not found, ML diarization bundle may be incomplete"
        )
        return []

    return [f"{config_path}{os.pathsep}pyannote/audio/telemetry"]


def _package_file_data_entry(package_name: str, filename: str) -> str | None:
    """Return an ``--add-data`` entry for a package-local file when present."""
    spec = _safe_find_spec(package_name)
    if spec is None or spec.origin is None:
        return None

    package_dir = Path(spec.origin).resolve().parent
    file_path = package_dir / filename
    if not file_path.exists():
        print(
            f"[deps] WARNING: {package_name}/{filename} not found, frozen bundle may be incomplete"
        )
        return None

    target_dir = package_name.replace(".", "/")
    return f"{file_path}{os.pathsep}{target_dir}"


def _default_data_entries() -> list[str]:
    defaults_yaml = PROJECT_ROOT / "src" / "voxfusion" / "config" / "defaults.yaml"
    gui_locales_dir = PROJECT_ROOT / "src" / "voxfusion" / "gui" / "locales"
    entries = [f"{defaults_yaml}{os.pathsep}voxfusion/config"]
    if gui_locales_dir.exists():
        entries.append(f"{gui_locales_dir}{os.pathsep}voxfusion/gui/locales")
    else:
        print(
            "[deps] WARNING: GUI locales directory not found, frozen GUI may fall back to raw i18n keys"
        )
    entries.extend(_customtkinter_data_entries())
    entries.extend(_pyannote_data_entries())
    # lightning version files are only needed when torch backends are bundled;
    # collecting them triggers PyInstaller's isolated subprocess analysis which
    # segfaults when torch.distributed is imported transitively on Linux.
    # entries.extend(_package_file_data_entry(...) for lightning packages)
    entries.extend(_ffmpeg_data_entries())
    return entries


def _platform_tag() -> str:
    machine = platform.machine().lower() or "unknown"
    system_name = platform.system().lower() or "unknown"
    return f"{system_name}-{machine}"


def _copy_python_dll(bundle_dir: Path) -> None:
    """Copy python3XX.dll next to the EXE for reliable loading on Windows.

    PyInstaller places the DLL in _internal/ and uses SetDllDirectory to
    expose it, but some Windows 11 security configurations prevent this.
    Having the DLL in the same directory as the EXE is always found first
    by the Windows DLL loader without any extra API calls.
    """
    if platform.system().lower() != "windows":
        return
    dll_name = f"python{sys.version_info.major}{sys.version_info.minor}.dll"
    src = Path(sys.executable).parent / dll_name
    if not src.exists():
        print(f"[dll] WARNING: {dll_name} not found at {src}, skipping copy")
        return
    dst = bundle_dir / dll_name
    if not dst.exists():
        shutil.copy2(src, dst)
        print(f"[dll] copied {dll_name} to bundle root for reliable loading")


def build_target(
    target: BinaryTarget,
    *,
    version_file: Path,
    include_zip: bool,
    backends: set[str],
) -> Path:
    """Build one binary target and optionally package to ZIP."""
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    pyinstaller_work = BUILD_DIR / "pyinstaller-work" / target.name
    pyinstaller_spec = BUILD_DIR / "pyinstaller-spec"
    pyinstaller_work.mkdir(parents=True, exist_ok=True)
    pyinstaller_spec.mkdir(parents=True, exist_ok=True)

    command = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        "--onedir",
        "--name",
        target.name,
        "--distpath",
        str(DIST_DIR),
        "--workpath",
        str(pyinstaller_work),
        "--specpath",
        str(pyinstaller_spec),
    ]
    command.extend(["--paths", str(PROJECT_ROOT / "src")])

    if platform.system().lower() == "windows" and version_file.exists():
        command.extend(["--version-file", str(version_file)])

    icon = _get_icon_path()
    if icon:
        command.extend(["--icon", str(icon)])
        print(f"[icon] {icon}")
    else:
        print(
            "[icon] WARNING: no icon found in assets/.\n"
            "  Run: python scripts/make_icon.py   (requires: pip install Pillow)"
        )

    command.append("--windowed" if target.windowed else "--console")

    # Exclude torch submodules that crash PyInstaller's submodule collection
    # with SIGSEGV during _collect_submodules(). These are not needed for
    # inference (only for distributed training).
    for exclude in (
        "torch.distributed",
        "torch.testing",
        "torch._C._distributed_c10d",
    ):
        command.extend(["--exclude-module", exclude])

    # Disable PyInstaller's built-in hook for torch which triggers a segfault
    # when collecting torch.distributed.optim submodules on Linux.
    # Use custom hook directory with a safe torch hook override.
    custom_hooks = PROJECT_ROOT / "scripts" / "pyinstaller-hooks"
    if custom_hooks.is_dir():
        command.extend(["--additional-hooks-dir", str(custom_hooks)])

    for imp in _hidden_imports(backends=backends):
        command.extend(["--hidden-import", imp])

    # Collect all files (including native DLLs) from packages that need it.
    # Only packages that are actually installed are included.
    for pkg in _collect_all_packages(backends=backends):
        command.extend(["--collect-all", pkg])

    for entry in _default_data_entries():
        command.extend(["--add-data", entry])

    launcher = _write_launcher(target)
    command.append(str(launcher))

    print(f"\n[build] {target.name}")
    print(" ".join(command))
    subprocess.run(command, cwd=PROJECT_ROOT, check=True)

    bundle_dir = DIST_DIR / target.name
    _copy_python_dll(bundle_dir)
    if not include_zip:
        return bundle_dir

    archive_basename = DIST_DIR / f"{target.name}-{_platform_tag()}"
    zip_path = archive_basename.with_suffix(".zip")
    if zip_path.exists():
        zip_path.unlink()

    shutil.make_archive(
        base_name=str(archive_basename),
        format="zip",
        root_dir=str(DIST_DIR),
        base_dir=target.name,
    )
    print(f"[zip] {zip_path}")
    return zip_path


def main() -> int:
    """Main build flow."""
    args = parse_args()

    if not args.skip_install:
        _install_dependencies()
    else:
        print("[deps] Skipping dependency installation (--skip-install).")

    version, version_tuple = load_version()
    version_file = write_version_file(
        company_name=args.company_name,
        product_name=args.product_name,
        version_str=version,
        version_tuple=version_tuple,
    )

    selected_targets: list[BinaryTarget]
    if args.target == "all":
        selected_targets = [TARGETS["gui"], TARGETS["cli"]]
    else:
        selected_targets = [TARGETS[args.target]]

    backends = _parse_backends(args.backends)
    print(f"[backends] building with: {', '.join(sorted(backends))}")

    for target in selected_targets:
        build_target(
            target,
            version_file=version_file,
            include_zip=not args.no_zip,
            backends=backends,
        )

    print("\nBuild completed.")
    if platform.system().lower() == "windows":
        print(
            "Windows note: ask users to open ZIP file properties and click "
            "'Unblock' before extraction."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
